server:
  port: 9787
  address: localhost
spring:
  application:
    name: BookSystem
  datasource:
    url: jdbc:mysql://localhost:3306/db_booksystem?useSSL=false&serverTimezone=UTC
    username: root
    password: 114514
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 123456
  servlet:
    multipart:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/*Mapper.xml
  type-aliases-package: com/example/booksystem/core/entity







